Paven/ViewModels/ShoppingCartViewModel.cs
using Paven.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Paven.ViewModels
{
    public class ShoppingCartViewModel
    {
        [Key]
        public List<Cart> CartItems { get; set; }
        public double CartTotal { get; set; }
    }
}

Paven/Controllers/CheckoutController.cs
using Paven.Models;
using Syncfusion.Pdf;
using Syncfusion.Pdf.Graphics;
using Syncfusion.Pdf.Grid;
using System;
using System.Collections.Generic;
using System.Data;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Paven.Controllers
{
    public class CheckoutController : Controller
    {
        ApplicationDbContext dB = new ApplicationDbContext();        

        // GET: Checkout
        public ActionResult Index()
        {
            return View();
        }
                
        [Authorize]
        public async Task<ActionResult> Payment() //The Method That Handles All Transactions
        {
            //Variables Required For Tables
            double deliveryFee = 0;
            int numProducts = 0;

            //Get Current Cart
            var cart = ShoppingCart.GetCart(this.HttpContext);

            //Create New Sale
            Sale sale = new Sale();
            sale.SaleDate = DateTime.Now.ToString();           

            
            numProducts = cart.GetCount();

            if (numProducts == 1)
            {
                deliveryFee = 60;
            }
            else if (numProducts <= 3)
            {
                deliveryFee = 80;
            }
            else
            {
                deliveryFee = 100;
            }

            //Customer Details
            sale.Email = User.Identity.Name;
            sale.CustomerName = User.Identity.GetName();
            sale.Address = User.Identity.GetAddress();
            sale.City = User.Identity.GetCity();
            sale.State = User.Identity.GetState();
            sale.PostalCode = User.Identity.GetPostalCode();
            sale.Country = User.Identity.GetCountry();
            sale.PhoneNumber = User.Identity.GetPhoneNo();

            //Sale Total
            double SaleFinal = cart.GetTotal();
            sale.SaleTotal = SaleFinal + deliveryFee;            

            //Check product stock
            var x = cart.GetCartItems();
            List<Product> chck = (from q in dB.Products
                                  select q).ToList();

            foreach (var items in x)
            {
                foreach (Product c in chck)
                {
                    if (items.ProductId == c.ProductId)
                    {
                        c.ProductStock += items.Count; //Temporary stock check pause... Make this -= to reduce stock
                        if (c.ProductStock == 0)
                        {
                            c.isActive = false; //Sets item to inactive due to stock being zero. 
                        }
                    }
                }
            }

            //Save Order to Delivery and Sale Table    
            Delivery delivery = new Delivery
            {
                SaleId = sale.SaleId,
                DeliveryFee = deliveryFee,
                CurrentLocation = "394 Smith Street, Durban, 4001",
                isDelivered = false
            };
            dB.Deliveries.Add(delivery);
            dB.Sales.Add(sale);
            await dB.SaveChangesAsync();

            double FinalCost = cart.GetTotal() + cart.GetDeliveryFee();

            //SaleDetail Saved Using Helper Method
            string orderId = sale.SaleId.ToString();
            sale = cart.CreateOrder(sale);

            //New Email.
            //Creates a new PDF document
            PdfDocument document = new PdfDocument();
            //Adds page settings
            document.PageSettings.Orientation = PdfPageOrientation.Portrait;
            document.PageSettings.Margins.All = 50;
            //Adds a page to the document
            PdfPage page = document.Pages.Add();
            PdfGraphics graphics = page.Graphics;
            //Loads the image from disk
            PdfImage image = PdfImage.FromFile(Server.MapPath("~/Images/EmailLogo.png"));
            RectangleF bounds = new RectangleF(10, 10, 200, 200);
            //Draws the image to the PDF page
            page.Graphics.DrawImage(image, bounds);
            PdfBrush solidBrush = new PdfSolidBrush(new PdfColor(126, 151, 173));
            bounds = new RectangleF(0, bounds.Bottom + 90, graphics.ClientSize.Width, 30);
            //Draws a rectangle to place the heading in that region.
            graphics.DrawRectangle(solidBrush, bounds);
            //Creates a font for adding the heading in the page
            PdfFont subHeadingFont = new PdfStandardFont(PdfFontFamily.TimesRoman, 14);
            //Creates a text element to add the invoice number
            PdfTextElement element = new PdfTextElement("Invoice " + sale.SaleId.ToString() + " for" + " " + sale.CustomerName, subHeadingFont);
            element.Brush = PdfBrushes.White;

            //Draws the heading on the page
            PdfLayoutResult res = element.Draw(page, new PointF(10, bounds.Top + 8));
            string currentDate = "Date Purchased " + sale.SaleDate.ToString();
            //Measures the width of the text to place it in the correct location
            SizeF textSize = subHeadingFont.MeasureString(currentDate);
            PointF textPosition = new PointF(graphics.ClientSize.Width - textSize.Width - 10, res.Bounds.Y);
            //Draws the date by using DrawString method
            graphics.DrawString(currentDate, subHeadingFont, element.Brush, textPosition);
            PdfFont timesRoman = new PdfStandardFont(PdfFontFamily.TimesRoman, 10);
            //Creates text elements to add the address and draw it to the page.
            element = new PdfTextElement("Bill To " + sale.Address.ToString() + ", " + sale.City + ", " + sale.State, timesRoman);
            element.Brush = new PdfSolidBrush(new PdfColor(126, 155, 203));
            res = element.Draw(page, new PointF(10, res.Bounds.Bottom + 25));
            element = new PdfTextElement("Total Price R" + sale.SaleTotal.ToString(), timesRoman);
            element.Brush = new PdfSolidBrush(new PdfColor(126, 155, 203));
            res = element.Draw(page, new PointF(10, res.Bounds.Bottom + 25));           
            PdfPen linePen = new PdfPen(new PdfColor(126, 151, 173), 0.70f);
            PointF startPoint = new PointF(0, res.Bounds.Bottom + 3);
            PointF endPoint = new PointF(graphics.ClientSize.Width, res.Bounds.Bottom + 3);
            //Draws a line at the bottom of the address
            graphics.DrawLine(linePen, startPoint, endPoint);

            //Creates the datasource for the table
            DataTable invoiceDetails = new DataTable();

            //Add columns to the DataTable
            invoiceDetails.Columns.Add("Product Name");            
            invoiceDetails.Columns.Add("Quantity");
            invoiceDetails.Columns.Add("Price");

            //Add rows to the DataTable
            foreach (var item in sale.SaleDetails.Where(m => m.SaleId == sale.SaleId))
            {
                invoiceDetails.Rows.Add(new object[] { item.Product.ProductName, item.Quantity, item.Product.ProductPrice });
            }


            //Creates text elements to add the address and draw it to the page.



            //Creates a PDF grid
            PdfGrid grid = new PdfGrid();
            //Adds the data source
            grid.DataSource = invoiceDetails;
            //Creates the grid cell styles
            PdfGridCellStyle cellStyle = new PdfGridCellStyle();
            cellStyle.Borders.All = PdfPens.White;
            PdfGridRow header = grid.Headers[0];
            //Creates the header style
            PdfGridCellStyle headerStyle = new PdfGridCellStyle();
            headerStyle.Borders.All = new PdfPen(new PdfColor(126, 151, 173));
            headerStyle.BackgroundBrush = new PdfSolidBrush(new PdfColor(126, 151, 173));
            headerStyle.TextBrush = PdfBrushes.White;
            headerStyle.Font = new PdfStandardFont(PdfFontFamily.TimesRoman, 14f, PdfFontStyle.Regular);

            //Adds cell customizations
            for (int i = 0; i < header.Cells.Count; i++)
            {
                if (i == 0 || i == 1)
                    header.Cells[i].StringFormat = new PdfStringFormat(PdfTextAlignment.Left, PdfVerticalAlignment.Middle);
                else
                    header.Cells[i].StringFormat = new PdfStringFormat(PdfTextAlignment.Right, PdfVerticalAlignment.Middle);
            }

            //Applies the header style
            header.ApplyStyle(headerStyle);
            cellStyle.Borders.Bottom = new PdfPen(new PdfColor(217, 217, 217), 0.70f);
            cellStyle.Font = new PdfStandardFont(PdfFontFamily.TimesRoman, 12f);
            cellStyle.TextBrush = new PdfSolidBrush(new PdfColor(131, 130, 136));
            //Creates the layout format for grid
            PdfGridLayoutFormat layoutFormat = new PdfGridLayoutFormat();
            // Creates layout format settings to allow the table pagination
            layoutFormat.Layout = PdfLayoutType.Paginate;
            //Draws the grid to the PDF page.
            PdfGridLayoutResult gridResult = grid.Draw(page, new RectangleF(new PointF(0, res.Bounds.Bottom + 40), new SizeF(graphics.ClientSize.Width, graphics.ClientSize.Height - 100)), layoutFormat);

            MemoryStream outputStream = new MemoryStream();
            document.Save(outputStream);
            outputStream.Position = 0;

            var invoicePdf = new System.Net.Mail.Attachment(outputStream, System.Net.Mime.MediaTypeNames.Application.Pdf);
            string docname = "Invoice.pdf";
            invoicePdf.ContentDisposition.FileName = docname;

            MailMessage mail = new MailMessage();
            string emailTo = sale.Email;
            MailAddress from = new MailAddress("africanmagicsystem@gmail.com");
            mail.From = from;
            mail.Subject = "Your invoice for order number #" + sale.SaleId;

Paven/Controllers/ShoppingCartController.cs
using Paven.Models;
using Paven.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Paven.Controllers
{
    [Authorize]
    public class ShoppingCartController : Controller
    {
        ApplicationDbContext dB = new ApplicationDbContext();

        
        // GET: ShoppingCart
        public ActionResult Index()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            // Set up our ViewModel
            var viewModel = new ShoppingCartViewModel()
            {
                CartItems = cart.GetCartItems(),
                CartTotal = cart.GetTotal()
            };

            ViewBag.TotalCost = cart.GetTotal() + cart.GetDeliveryFee();
            ViewBag.ShippingCost = cart.GetDeliveryFee();
            // Return the view
            return View(viewModel);
        }

        //Add To Cart       
        [HttpPost]
        public ActionResult AddToCart(int id)
        {
            // Retrieve the item from the database
            var addedItem = dB.Products
                .Single(product => product.ProductId == id);

            // Add it to the shopping cart
            var cart = ShoppingCart.GetCart(this.HttpContext);

            int count = cart.AddToCart(addedItem);


            var results = new ShoppingCartRemoveViewModel
            {
                Message = Server.HtmlEncode(addedItem.ProductName) +
                    " has been added to your shopping cart.",
                CartTotal = cart.GetTotal(),
                CartCount = cart.GetCount(),
                ItemCount = count,
                DeleteId = id
            };
            return Json(results);           
        }
        //End

        //Remove From Cart
        [HttpPost]
        public ActionResult RemoveFromCart(int id)
        {
            // Remove the item from the cart
            var cart = ShoppingCart.GetCart(this.HttpContext);

            // Get the name of the item to display confirmation

            // Get the name of the album to display confirmation
            string itemName = dB.Products
                .Single(item => item.ProductId == id).ProductName;

            // Remove from cart
            int itemCount = cart.RemoveFromCart(id);

            // Display the confirmation message
            var results = new ShoppingCartRemoveViewModel
            {
                Message = "One (1) " + Server.HtmlEncode(itemName) +
                    " has been removed from your shopping cart.",
                CartTotal = cart.GetTotal(),
                CartCount = cart.GetCount(),
                ItemCount = itemCount,
                DeleteId = id
            };
            return Json(results);
        }
        //End

        // GET: /ShoppingCart/CartSummary
        [ChildActionOnly]
        public ActionResult CartSummary()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            ViewData["CartCount"] = cart.GetCount();
            return PartialView("CartSummary");
        }


        // GET: ShoppingCart/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ShoppingCart/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ShoppingCart/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: ShoppingCart/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: ShoppingCart/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: ShoppingCart/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ShoppingCart/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Paven/Views/ShoppingCart/CartSummary.cshtml
<a href='@Url.Action("Index", "ShoppingCart")'><strong>Cart</strong>  <span id="cart-status" class="badge">@ViewData["CartCount"]</span></a>

Paven/Views/ShoppingCart/Index.cshtml
@model Paven.ViewModels.ShoppingCartViewModel
@{
    ViewBag.Title = "Shopping Cart";
}

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script type="text/javascript">
    $(function () {
        // Document.ready -> link up remove event handler
        $(".RemoveLink").click(function () {
            // Get the id from the link
            var recordToDelete = $(this).attr("data-id");
            if (recordToDelete != '') {
                // Perform the ajax post
                $.post("/ShoppingCart/RemoveFromCart", { "id": recordToDelete },
                    function (data) {
                        // Successful requests get here
                        // Update the page elements
                        if (data.ItemCount == 0) {
                            $('#row-' + data.DeleteId).fadeOut('slow');
                        } else {
                            $('#item-count-' + data.DeleteId).text(data.ItemCount);
                        }
                        $('#cart-total').text(data.CartTotal);
                        $('#update-message').text(data.Message);
                        $('#cart-status').text(data.CartCount);
                    });
            }
        });
    });
</script>
<h3 class="text-center text-success">
    <em>Review</em> your cart:
</h3>

@{

    if (Model.CartItems.Count > 0)
    {
        <div class="panel panel-info">
            <div class="panel-heading">
                <h3 class="panel-title">Order Summary</h3>
            </div>
            <div class="panel-body">

                <div id="update-message">
                </div>
                <table class="table table-striped table-hover ">
                    <thead>
                        <tr>
                            <th>
                                Product:
                            </th>
                            <th>
                                Price:
                            </th>
                            <th>
                                Quantity:
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    @foreach (var item in Model.CartItems)
                    {
                        <tr id="row-@item.ProductId">
                            <td>
                                @Html.ActionLink(item.Product.ProductName, "Details", "Products", new { id = item.ProductId }, null)
                            </td>
                            <td>
                                &#82;@item.Product.ProductPrice
                            </td>
                            <td id="item-count-@item.ProductId">
                                @item.Count
                            </td>
                            <td>
                                <a href="#" class="RemoveLink"
                                   data-id="@item.ProductId">
                                    Remove
                                    from cart
                                </a>
                            </td>
                        </tr>
                    }
                    <tr class="info">
                        <td>
                            Total
                        </td>
                        <td></td>
                        <td></td>
                        <td id="cart-total">
                            &#82;@Model.CartTotal
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Shipping Fee
                        </td>
                        <td></td>
                        <td></td>
                        <td id="cart-total">
                            &#82;@ViewBag.ShippingCost
                        </td>
                    </tr>
                    <tr class="success">
                        <td>
                            Total Including Shipping
                        </td>
                        <td></td>
                        <td></td>
                        <td id="cart-total">
                            <strong>&#82;@ViewBag.TotalCost</strong>
                        </td>
                    </tr>
                    <tfoot>Please ensure that all products in cart are correct before checking out.</tfoot>
                </table>
                <button type="button" class="btn btn-success btn-sm" onclick="location.href='@Url.Action("Payment", "Checkout")'">
                    Confirm and Pay &#82;@ViewBag.TotalCost
                </button>
            </div>
        </div>

    }
    else
    {
        <div>
            <p>
                There are no items in your cart currently. Please shop for something and add items..
            </p>
        </div>
    }
}